# FROM humpedli/docker-pure-ftpd-mysql

# ADD pure-ftpd.conf /etc/pure-ftpd/pure-ftpd.conf
# RUN chmod 644 /etc/pure-ftpd/pure-ftpd.conf

# ADD pureftpd-mysql.conf /etc/pure-ftpd/pureftpd-mysql.conf
# RUN chmod 644 etc/pure-ftpd/pureftpd-mysql.conf


# FROM "humpedli/docker-pure-ftpd-mysql"

# ADD pure-ftpd.conf2 /etc/pure-ftpd/pure-ftpd.conf
# RUN chmod 644 /etc/pure-ftpd/pure-ftpd.conf


FROM crazymax/pure-ftpd